apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-policies
  namespace: openshift-gitops
spec:
  destination:
    namespace: policies
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/kfrankli/gitops-rhacm-policies.git
    targetRevision: main
    path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
